name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ../dive-site-russia-deply/docker-compose up -d --build
      - name: Migrations
        run: ../dive-site-russia-deply/docker-compose exec api php artisan migrate
