kind: pipeline
type: exec
name: default

trigger:
  branch:
    - master

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - cd ../dive-site-russia/deploy && docker-compose up -d --build --no-deps api
