kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build --tag dive-site-russia .
      - docker-compose -f /home/strftime/dive-site-russia-deploy/docker-compose.yml up -d --no-deps --remove-orphans api
