name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cd home/strftime/dive-site-russia-deploy && docker-compose up -d --build --no-deps api
      - name: Migrations
        run: cd home/strftime/dive-site-russia-deploy && docker-compose exec api php artisan migrate
