name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: docker-compose -f ../dive-site-russia-deploy/docker-compose.yml up -d --build --no-deps api
      - name: Migrations
        run: docker-compose -f ../dive-site-russia-deploy/docker-compose.yml exec api php artisan migrate
